uncaught exception: FOO
	at bar
	at foo
	at main_0
	at add__sfirst__stask__lambda0
	at call_675
	at then__lambda0__lambda0
	at call_675
	at catch_0__lambda0
	at call_672
	at catch_1
	at catch_0
	at then__lambda0
	at call_1221
	at invoke__saction
	at do__stask
	at thread__sfunction
