exit code: 1
stderr:
uncaught exception: FOO
	at bar
	at foo
	at main_0
	at add__sfirst__stask__lambda0
	at call_688
	at then__lambda0__lambda0
	at call_688
	at catch_0__lambda0
	at call_685
	at catch_1
	at catch_0
	at then__lambda0
	at call_1240
	at invoke__saction
	at do__stask
	at thread__sfunction
