uncaught exception: FOO
	at bar
	at foo
	at main_0
	at add__sfirst__stask__lambda0
	at call__sw__sctx_587
	at then__lambda0__lambda0
	at call__sw__sctx_587
	at catch_0__lambda0
	at call__sw__sctx_584
	at catch_1
	at catch_0
	at then__lambda0
	at call__sw__sctx_1110
	at invoke__saction
	at do__stask
	at thread__sfunction
