exit code: 0
stderr:
test/end-to-end/compile-errors/fun-closure-errors.crow 6:13-6:16 Can't access 'fut' in a 'data' lambda because it is of 'shared' type 'void^'.
test/end-to-end/compile-errors/fun-closure-errors.crow 8:28-8:29 Can't access 'x' in a 'shared' lambda because it is a 'mut' local.
test/end-to-end/compile-errors/fun-closure-errors.crow 11:32-11:33 Can't access 'y' in a 'data' lambda because it is of 'mut' type 'nat64 mut[]'.
test/end-to-end/compile-errors/fun-closure-errors.crow 12:34-12:35 Can't access 'y' in a 'shared' lambda because it is of 'mut' type 'nat64 mut[]'.
test/end-to-end/compile-errors/fun-closure-errors.crow 14:27-14:30 Can't call a 'summon' function from inside a 'data' lambda. 'sum void()' (from test/end-to-end/compile-errors/fun-closure-errors.crow line 28).
test/end-to-end/compile-errors/fun-closure-errors.crow 16:30-16:33 Can't call a 'summon' function from inside a 'data' lambda. 'sum void()' (from test/end-to-end/compile-errors/fun-closure-errors.crow line 28).
test/end-to-end/compile-errors/fun-closure-errors.crow 19:9-19:18 Can't call a 'summon' function from inside a 'data' lambda. 'sum void()' (from test/end-to-end/compile-errors/fun-closure-errors.crow line 28).
